config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links

  root 'links#index'
  resources :views, path: :v, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user, optional: true
  has_many :views, dependent: :destroy
  validates :url, presence: true

  scope :recent_first, -> { order(created_at: :desc) }

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def self.find(id)
    super(ShortCode.decode(id))
  end

  def to_param
    ShortCode.encode(id)
  end

  def domain
    URI(url).host rescue URI::InvalidError
  end

  def editable_by?(user)
    return false unless user_id?
    user_id == user&.id
  end
end

app/models/metadata.rb
require "open-uri"

class Metadata
  attr_reader :doc

  def self.retrieve_from(url)
    new(URI.open(url))
  rescue
    new
  end

  def initialize(html=nil)
    @doc = Nokogiri::HTML(html)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    doc.at_css("title")&.text
  end

  def description
    meta_tag_content "description"
  end

  def image
    meta_tag_content "og:image", name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch("content", nil)&.text
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length

  def self.encode(number)
    return ALPHABET.first if number.zero? || number.nil?
    result = ""

    while number > 0
      index = number % BASE
      char = ALPHABET[index]
      result.prepend char
      number = number / BASE
    end

    result
  end

  def self.decode(string)
    number = 0

    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET.index(char)
      number += index * power
    end

    number
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :links
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :check_if_editable, only: [:edit, :update, :destroy]

  def index
    @pagy, @links = pagy(Link.recent_first, items: 10)
    @link ||= Link.new 
  end

  def create
    @link = Link.new(link_params.with_defaults(user: current_user))
    if @link.save
      respond_to do |format|
        format.html { redirect_to @link }
        format.turbo_stream { render turbo_stream: [
          turbo_stream.prepend("links", @link),
          turbo_stream.replace("link_form", partial: "links/form", locals: { link: Link.new })
        ] }
      end
    else
      index # caso o link não seja salvo, a lista de links é renderizada novamente
      render :index, status: :unprocessable_entity
    end
  end

  def show ; end

  def edit ; end

  def update 
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    if @link.destroy
      redirect_to root_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end

  def check_if_editable
    if @link.editable_by?(current_user)
      true
    else
      redirect_to @link, alert: "You cannot edit this link"
    end
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  rescue_from ActiveRecord::RecordNotFound do 
    redirect_to root_path, alert: "Link not found"
  end

  def show
    @link.views.create!(ip: request.remote_ip, user_agent: request.user_agent)
    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
  </head>

  <body>
    <%= render partial: 'shared/navbar'%>

    <div class="container mx-auto mt-20 px-8"> 

      <%= render partial: 'shared/alert' if alert.present? %>
      <%= render partial: 'shared/notice' if notice.present? %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link, id: 'link_form' ,html: { class: 'flex' } do |f|%>
  <%= f.url_field :url, required: true ,class: 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full mb-2 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-full-name', placeholder: 'https://www.example.com' %>
  <%= f.submit "Shorten", class: 'bg-indigo-500 text-white active:bg-indigo-600 font-bold uppercase text-sm px-4 py-25 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150 ml-2'%>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= turbo_stream_from link %>

  <div class="grid grid-cols-8 py-4">

    <div class='col-span-5'>
      <%= link_to view_path(link), target: :_blank, data: { turbo: false } do %>
        <%= image_tag "https://www.google.com/s2/favicons?domain=#{link.domain}", class: 'inline-block m-0'%>
        <%= link.title || link.url %>
        <%= tag.div link.description, class: "text-xs text-gray-700" %>>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>  

    <div class='col-span-2 text-center text-sm mt-1.5'>
      <%= link_to pluralize(link.views_count, 'view'), link, class: 'bg-purple-500 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150' %>
    </div>

    <div class='text-sm'>
      <%= button_tag 'Copy', class: 'bg-indigo-500 text-white active:bg-indigo-600 font-bold uppercase text-xs px-4 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150', data: {controller: "clipboard", clipboard_text: view_url(link)} %>
    </div>

  </div>
<% end %>

app/views/links/edit.html.erb
<h1 class="text-6xl font-bold leading-normal mt-0 text-indigo-500">Edit</h1>

<%= render partial: 'form', locals: { link: @link } %>

<div class="flex gap-1 items-center mt-4">
  <%= link_to "Cancel", @link, class: 'bg-purple-500 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150' %>
  <%= button_to "Delete", @link, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: 'bg-indigo-500 text-white active:bg-indigo-600 font-bold uppercase text-xs px-4 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150' %>
</div>

app/views/links/index.html.erb
<h1 class="text-6xl font-bold leading-normal mt-0 text-indigo-500">Welcome</h1>
<%= render partial: 'form', locals: { link: @link }%>

<div id="links" class='mt-8 flex flex-col divide-y divide-gray-100'>
  <%= render @links %>

  <% if @pagy.pages > 1 %>
    <div class='pt-8 mb-16 text-center'>
      <%== pagy_nav @pagy %>
    </div>
  <% end %>
</div>

app/views/links/show.html.erb
<h1 class="text-6xl font-bold leading-normal mt-0 text-indigo-500">Click counts</h1>

<div class="grid grid-cols-2 p-2 bg-gray-200 shadow rounded-lg mb-4">
  <div class="text-xl text-blue-600 mb-2">
    <%= image_tag "https://www.google.com/s2/favicons?domain=#{@link.domain}", class: 'inline-block h-6'%>
    <%= link_to "#{@link.url}", view_path(@link), target: :_blank, data: { turbo: false } %>
  </div>
  <div class="text-xl text-gray-700">
    <%= pluralize(@link.views_count, 'view') %>
  </div>
</div>

<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>
<div class="mt-4">
  <%= link_to "Edit", edit_link_path(@link), class: 'no-underline text-white bg-indigo-500 border border-solid border-indigo-500 hover:bg-white hover:text-indigo-500 active:bg-indigo-600 font-bold uppercase text-sm rounded max-w-xs outline-none px-6 py-3  py-3 focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150' if @link.editable_by?(current_user) %>
  <%= link_to 'Back to home page', root_path, class: 'no-underline text-indigo-500 bg-transparent border border-solid border-indigo-500 hover:bg-indigo-500 hover:text-white active:bg-indigo-600 font-bold uppercase text-sm rounded max-w-xs outline-none px-6 py-3  py-3 focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150' %>
</div>

app/views/shared/_alert.html.erb
<div class="alert">
  <div class="alert-content">
    <div class="text-white px-6 py-4 border-0 rounded relative mb-4 bg-indigo-500">
      <span class="text-xl inline-block mr-5 align-middle">
        
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
        </svg>

      </span>
      <span class="inline-block align-middle mr-8">
        <b class="capitalize">Alert!</b> <%= alert %>
      </span>
      <button class="absolute bg-transparent text-2xl font-semibold leading-none right-0 top-0 mt-4 mr-6 outline-none focus:outline-none" onclick="this.closest('.alert').style.display='none'">
        <span>×</span>
      </button>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="relative flex flex-wrap items-center justify-between px-2 py-3 bg-indigo-500 mb-3">
  <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
    <div class="w-full relative flex justify-between lg:w-auto  px-4 lg:static lg:block lg:justify-start">
      <%= link_to "Url Shortener", root_path, class: 'text-sm font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase text-white' %>
      <button class="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none" type="button">
        <span class="block relative w-6 h-px rounded-sm bg-white"></span>
        <span class="block relative w-6 h-px rounded-sm bg-white mt-1"></span>
        <span class="block relative w-6 h-px rounded-sm bg-white mt-1"></span>
      </button>
    </div>
    <div class="lg:flex flex-grow items-center" id="example-navbar-warning">
      <ul class="flex flex-col lg:flex-row list-none ml-auto">
          <% if user_signed_in? %>
           <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, class: 'px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75', method: :get %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class: 'px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75' %>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notice.html.erb
<div class="alert">
  <div class="alert-content">
    <div class="text-white px-6 py-4 border-0 rounded relative mb-4 bg-indigo-500">
      <span class="text-xl inline-block mr-5 align-middle">
        
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
      </svg>

      </span>
      <span class="inline-block align-middle mr-8">
        <b class="capitalize">Noticet!</b> <%= notice %>
      </span>
      <button class="absolute bg-transparent text-2xl font-semibold leading-none right-0 top-0 mt-4 mr-6 outline-none focus:outline-none" onclick="this.closest('.alert').style.display='none'">
        <span>×</span>
      </button>
    </div>
  </div>
</div>